package initialize

import (
	"achilles/api"
	"achilles/api/admin"
	_ "achilles/docs"
	"achilles/global"
	"achilles/middleware"
	"net/http"

	"github.com/gin-gonic/gin"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

// 初始化总路由

func Routers() *gin.Engine {
	r := gin.Default()
	r.StaticFS(global.GVA_CONFIG.Local.Path, http.Dir(global.GVA_CONFIG.Local.Path)) // 为用户头像和文件提供静态地址
	global.GVA_LOG.Info("use middleware logger")
	r.Use(middleware.Cors()) // cors allow all
	// r.Use(middleware.CorsByRules()) // cors allow by rules
	global.GVA_LOG.Info("use middleware cors")
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	global.GVA_LOG.Info("register swagger handler")
	admin.InitRouter(r.Group("/api/admin"))
	exampleRouter := api.RouterGroupApp.Example
	autocodeRouter := api.RouterGroupApp.Autocode
	PublicGroup := r.Group("")
	{
		// 健康监测
		PublicGroup.GET("/health", func(c *gin.Context) {
			c.JSON(200, "ok")
		})
	}
	privateGroup := r.Group("")
	privateGroup.Use(middleware.JWTAuth()).Use(middleware.CasbinHandler())
	{
		exampleRouter.InitExcelRouter(privateGroup)                 // 表格导入导出
		exampleRouter.InitCustomerRouter(privateGroup)              // 客户路由
		exampleRouter.InitFileUploadAndDownloadRouter(privateGroup) // 文件上传下载功能路由

		// Code generated by achilles Begin; DO NOT EDIT.
		autocodeRouter.InitSysAutoCodeExampleRouter(privateGroup)
		// Code generated by achilles End; DO NOT EDIT.
	}

	InstallPlugin(PublicGroup, privateGroup) // 安装插件

	global.GVA_LOG.Info("router register success")
	return r
}
